services: 
  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  location-service:
    build: 
      context: ./services/location-service
      dockerfile: Dockerfile
    container_name: location-service
    depends_on:
      - postgres
    ports:
      - "50051:50051"
      - "8080:8080"
    env_file:
    - ./services/location-service/.env

volumes:
  postgres_data: