server: 
  port: 50051
  weather_service_port: 50052
  analytic_service_port: 50053
  gateway_port: 8080

database:
  host: "postgres"
  port: "5432"
  sslmode: "disable"

kafka:
  brokers: "kafka:9092"
  location_topic: "location-added-topic"

