// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticService_GetAnalyticsById_FullMethodName = "/analytics.AnalyticService/GetAnalyticsById"
)

// AnalyticServiceClient is the client API for AnalyticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticServiceClient interface {
	GetAnalyticsById(ctx context.Context, in *GetAnalyticsByIdRequest, opts ...grpc.CallOption) (*GetAnalyticsByIdResponse, error)
}

type analyticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticServiceClient(cc grpc.ClientConnInterface) AnalyticServiceClient {
	return &analyticServiceClient{cc}
}

func (c *analyticServiceClient) GetAnalyticsById(ctx context.Context, in *GetAnalyticsByIdRequest, opts ...grpc.CallOption) (*GetAnalyticsByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalyticsByIdResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetAnalyticsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticServiceServer is the server API for AnalyticService service.
// All implementations must embed UnimplementedAnalyticServiceServer
// for forward compatibility.
type AnalyticServiceServer interface {
	GetAnalyticsById(context.Context, *GetAnalyticsByIdRequest) (*GetAnalyticsByIdResponse, error)
	mustEmbedUnimplementedAnalyticServiceServer()
}

// UnimplementedAnalyticServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticServiceServer struct{}

func (UnimplementedAnalyticServiceServer) GetAnalyticsById(context.Context, *GetAnalyticsByIdRequest) (*GetAnalyticsByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalyticsById not implemented")
}
func (UnimplementedAnalyticServiceServer) mustEmbedUnimplementedAnalyticServiceServer() {}
func (UnimplementedAnalyticServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalyticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticServiceServer will
// result in compilation errors.
type UnsafeAnalyticServiceServer interface {
	mustEmbedUnimplementedAnalyticServiceServer()
}

func RegisterAnalyticServiceServer(s grpc.ServiceRegistrar, srv AnalyticServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticService_ServiceDesc, srv)
}

func _AnalyticService_GetAnalyticsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalyticsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetAnalyticsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetAnalyticsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetAnalyticsById(ctx, req.(*GetAnalyticsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticService_ServiceDesc is the grpc.ServiceDesc for AnalyticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticService",
	HandlerType: (*AnalyticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnalyticsById",
			Handler:    _AnalyticService_GetAnalyticsById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
